CSP-lib: Constraint Satisfaction Problem Solver Library: src/csp.h File Reference
csp.h File Reference
Header file for the CSP (Constraint Satisfaction Problem) library.
#include <stdbool.h>
#include <stddef.h>
Typedefs
typedef bool CSPChecker(const CSPConstraint *, const size_t *, const void *)
The check function of a CSP constraint.
typedef struct _CSPConstraint CSPConstraint
The constraint of a CSP problem.
typedef struct _CSPProblem CSPProblem
The CSP problem.
Functions
CSPConstraint * csp_constraint_create (size_t arity, CSPChecker *check)
Creates a new constraint with the specified arity and check function.
void csp_constraint_destroy (CSPConstraint *constraint)
Destroys a constraint and frees all associated resources.
size_t csp_constraint_get_arity (const CSPConstraint *constraint)
Gets the arity of a constraint.
CSPChecker * csp_constraint_get_check (const CSPConstraint *constraint)
Gets the check function associated with a constraint.
size_t csp_constraint_get_variable (const CSPConstraint *constraint, size_t index)
Gets the variable ID associated with a specific position in the constraint.
void csp_constraint_set_variable (CSPConstraint *constraint, size_t index, size_t variable)
Sets which CSP variable is related to a specific position in the constraint.
bool csp_constraint_to_check (const CSPConstraint *constraint, size_t index)
Determines if a constraint can be checked at the current stage of problem solving.
bool csp_finish (void)
Finalizes the CSP library.
bool csp_init (void)
Initializes the CSP library.
bool csp_initialised (void)
Checks if the CSP library is initialized.
bool csp_problem_backtrack (const CSPProblem *csp, size_t *values, const void *data, size_t index)
Recursively solves the CSP problem using backtracking from a given variable.
CSPProblem * csp_problem_create (size_t num_domains, size_t num_constraints)
Creates a new CSP problem instance with the specified parameters.
void csp_problem_destroy (CSPProblem *csp)
Destroys a CSP problem instance and frees all associated resources.
CSPConstraint * csp_problem_get_constraint (const CSPProblem *csp, size_t index)
Gets the constraint at the specified position in the CSP problem.
size_t csp_problem_get_domain (const CSPProblem *csp, size_t index)
Gets the domain size for a variable in the CSP problem.
size_t csp_problem_get_num_constraints (const CSPProblem *csp)
Gets the number of constraints in the CSP problem.
size_t csp_problem_get_num_domains (const CSPProblem *csp)
Gets the number of variables (domains) in the CSP problem.
bool csp_problem_is_consistent (const CSPProblem *csp, const size_t *values, const void *data, size_t index)
Checks if the current partial assignment is consistent with all constraints.
void csp_problem_set_constraint (CSPProblem *csp, size_t index, CSPConstraint *constraint)
Sets a constraint at the specified position in the CSP problem.
void csp_problem_set_domain (CSPProblem *csp, size_t index, size_t domain)
Sets the domain size for a variable in the CSP problem.
bool csp_problem_solve (const CSPProblem *csp, size_t *values, const void *data)
Solves a CSP problem using the basic backtracking algorithm.
Detailed Description
Header file for the CSP (Constraint Satisfaction Problem) library.
This file defines the core structures and functions for working with Constraint Satisfaction Problems. CSP is a mathematical problem where variables must be assigned values from their domains while satisfying a set of constraints. This library provides mechanisms for defining, manipulating and solving CSPs using various algorithms like backtracking and forward checking with heuristics.
Core Concepts
Variables and Domains: Each variable has a domain of possible values. In this library, variables are identified by their indices (0 to N-1), and each domain consists of values from 0 to domain_size-1.
Constraints: Relations that restrict the values variables can take simultaneously. The library supports constraints of arbitrary arity (number of variables involved).
Problem Structure: A collection of variables with their domains, and constraints between these variables. The goal is to assign a value to each variable from its domain, such that all constraints are satisfied.
Basic Workflow
Initialize the library: csp_init()
Create a problem: csp_problem_create()
Create and add constraints: csp_constraint_create(), csp_problem_add_constraint()
Solve the problem: Use one of the solving algorithms, e.g., solve_with_forward_checking()
Process the solution
Clean up resources: csp_problem_destroy(), csp_finish()
Author
Ch. Demko (original)
Date
3 mai 2025
Version
1.0
Definition in file csp.h.
Typedef Documentation
CSPChecker
typedef bool CSPChecker(const CSPConstraint *, const size_t *, const void *)
The check function of a CSP constraint.
This function type is used to check whether a constraint is satisfied for a given assignment of values to variables. It is provided by the user when creating constraints to define the specific conditions that must be met.
Parameters
constraint The constraint to check.
values The current assignment of values to variables.
data User-provided context data passed to the check function.
Returns
true if the constraint is satisfied, false otherwise.
Precondition
constraint != NULL
values != NULL
Definition at line 102 of file csp.h.
CSPConstraint
typedef struct _CSPConstraint CSPConstraint
The constraint of a CSP problem.
A constraint defines a relation between variables that must be satisfied for a valid solution. This is an opaque data type; use the API functions to interact with constraints.
Constraints are defined by:
A set of variables involved in the constraint
A checker function that determines if an assignment satisfies the constraint
Optional external data that can be passed to the checker function
See also
csp_constraint_create()
csp_constraint_set_variable()
csp_constraint_get_variable()
csp_constraint_get_arity()
csp_constraint_destroy()
Definition at line 64 of file csp.h.
CSPProblem
typedef struct _CSPProblem CSPProblem
The CSP problem.
Represents a complete Constraint Satisfaction Problem, containing the set of variables, their domains, and the constraints between them. This is an opaque data type; use the API functions to interact with CSP problems.
A CSP problem consists of:
A set of variables (identified by their indices)
A domain for each variable (values from 0 to domain_size-1)
A set of constraints that must be satisfied
See also
csp_problem_create()
csp_problem_add_constraint()
csp_problem_get_num_variables()
csp_problem_get_domain_size()
csp_problem_destroy()
Definition at line 85 of file csp.h.
Function Documentation
csp_constraint_create()
CSPConstraint * csp_constraint_create (size_t arity, CSPChecker * check) extern
Creates a new constraint with the specified arity and check function.
A constraint represents a relationship between variables that must be satisfied in a valid CSP solution. The arity is the number of variables involved in the constraint, and the check function determines whether a particular assignment of values satisfies the constraint.
Parameters
arity The number of variables involved in this constraint.
check The function that checks whether the constraint is satisfied.
Returns
A newly created constraint object, or NULL if memory allocation failed.
Precondition
The CSP library must be initialized via csp_init().
arity must be greater than 0.
check must be a valid function pointer (not NULL).
Postcondition
The constraint's variables are all initialized to 0.
The constraint's arity is set to the specified arity.
The constraint's check function is set to the specified check function.
Definition at line 71 of file csp.c.
References _CSPConstraint::arity, _CSPConstraint::check, csp_initialised(), and _CSPConstraint::variables.
Referenced by create_sudoku_problem(), main(), main(), test_lcv_basic(), test_prune_neighbors(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
csp_constraint_destroy()
void csp_constraint_destroy (CSPConstraint * constraint) extern
Destroys a constraint and frees all associated resources.
This function deallocates all memory used by the constraint object. After calling this function, the constraint pointer is no longer valid and should not be used.
Parameters
constraint The constraint to destroy.
Precondition
The CSP library must be initialized via csp_init().
constraint must not be NULL.
Postcondition
All memory associated with the constraint is freed.
Definition at line 99 of file csp.c.
References _CSPConstraint::arity, and csp_initialised().
Referenced by csp_problem_destroy(), and main().
csp_constraint_get_arity()
size_t csp_constraint_get_arity (const CSPConstraint * constraint) extern
Gets the arity of a constraint.
The arity refers to the number of variables involved in the constraint. For example, a binary constraint has arity 2, as it relates two variables.
Parameters
constraint The constraint whose arity to retrieve.
Returns
The number of variables involved in this constraint.
Precondition
The CSP library must be initialized via csp_init().
constraint must not be NULL.
Definition at line 105 of file csp.c.
References _CSPConstraint::arity, and csp_initialised().
Referenced by csp_forward_check_context_create(), fc_is_consistent(), main(), main(), order_values_lcv(), and prune_neighbors().
csp_constraint_get_check()
CSPChecker * csp_constraint_get_check (const CSPConstraint * constraint) extern
Gets the check function associated with a constraint.
The check function is used to determine whether the constraint is satisfied for a given assignment of values to variables.
Parameters
constraint The constraint whose check function to retrieve.
Returns
The function pointer to the constraint's check function.
Precondition
The CSP library must be initialized via csp_init().
constraint must not be NULL.
Definition at line 110 of file csp.c.
References _CSPConstraint::check, and csp_initialised().
Referenced by csp_forward_check_context_create(), fc_is_consistent(), main(), and prune_neighbors().
csp_constraint_get_variable()
size_t csp_constraint_get_variable (const CSPConstraint * constraint, size_t index) extern
Gets the variable ID associated with a specific position in the constraint.
This function retrieves which CSP variable is associated with a given position in the constraint.
Parameters
constraint The constraint to query.
index The position within the constraint (from 0 to arity-1).
Returns
The variable ID at the specified position in the constraint.
Precondition
The CSP library must be initialized via csp_init().
constraint must not be NULL.
index must be less than the constraint's arity.
Definition at line 121 of file csp.c.
References csp_initialised(), and _CSPConstraint::variables.
Referenced by csp_forward_check_context_create(), diff(), diff(), diff(), different(), fc_is_consistent(), main(), main(), order_values_lcv(), prune_neighbors(), sudoku_not_equal(), sudoku_not_equal_checker(), sudoku_preassigned(), sudoku_preassigned_checker(), sumLeq(), and sumLeq().
csp_constraint_set_variable()
void csp_constraint_set_variable (CSPConstraint * constraint, size_t index, size_t variable) extern
Sets which CSP variable is related to a specific position in the constraint.
This function specifies which CSP variable corresponds to each position in the constraint. For example, in a binary constraint between variables 3 and 5, you would call this function twice: once with index=0, variable=3 and once with index=1, variable=5.
Parameters
constraint The constraint to modify.
index The position within the constraint (from 0 to arity-1).
variable The variable ID to assign to this position in the constraint.
Precondition
The CSP library must be initialized via csp_init().
constraint must not be NULL.
index must be less than the constraint's arity.
Postcondition
The specified position in the constraint now references the given variable.
Definition at line 115 of file csp.c.
References csp_initialised(), and _CSPConstraint::variables.
Referenced by create_sudoku_problem(), main(), main(), test_lcv_basic(), test_prune_neighbors(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
csp_constraint_to_check()
bool csp_constraint_to_check (const CSPConstraint * constraint, size_t index) extern
Determines if a constraint can be checked at the current stage of problem solving.
During backtracking or forward checking, we only want to check constraints when all variables involved in the constraint have been assigned values. This function verifies whether all variables in the constraint have indices less than the provided index, which means they have already been assigned values in the current solving process.
Parameters
constraint The constraint to verify.
index The index of the current variable in the assignment process. All variables with indices less than this are considered assigned.
Returns
true if the constraint can be checked (all its variables have been assigned), false otherwise.
Precondition
The CSP library must be initialized via csp_init().
constraint must not be NULL.
Definition at line 127 of file csp.c.
References _CSPConstraint::arity, csp_initialised(), and _CSPConstraint::variables.
Referenced by csp_problem_is_consistent(), and main().
csp_finish()
bool csp_finish (void) extern
Finalizes the CSP library.
This function should be called when the CSP library is no longer needed. Due to the reference counting mechanism, the library is only actually finalized when the number of calls to csp_finish() matches the number of calls to csp_init().
Returns
true if the library was successfully finalized or decremented its reference count, false if the library was not initialized.
Postcondition
The library's internal reference counter is decremented.
If the reference counter reaches zero, all resources are freed.
Definition at line 52 of file csp.c.
References counter.
Referenced by main(), main(), main(), test_context_create_destroy(), test_lcv_basic(), test_prune_neighbors(), and test_solve_simple().
csp_init()
bool csp_init (void) extern
Initializes the CSP library.
This function must be called before using any other function in the CSP library. The library uses a reference counting mechanism, so each call to csp_init() must be matched with a corresponding call to csp_finish().
// Initialize the library
if (!csp_init()) {
    fprintf(stderr, "Failed to initialize CSP library\n");
    return EXIT_FAILURE;
}
// Use the library...
// Clean up when done
csp_finish();
Returns
true if the library was successfully initialized (or was already initialized), false otherwise.
Postcondition
The library's internal reference counter is incremented.
The library is ready for use.
Definition at line 34 of file csp.c.
References _verify(), and counter.
Referenced by main(), main(), main(), test_context_create_destroy(), test_lcv_basic(), test_prune_neighbors(), and test_solve_simple().
csp_initialised()
bool csp_initialised (void) extern
Checks if the CSP library is initialized.
This function can be used to check the initialization state of the library before attempting to use other functions.
Returns
true if the library is currently initialized, false otherwise.
Postcondition
The library state is unchanged.
Definition at line 67 of file csp.c.
References counter.
Referenced by _verify(), backtrack_fc(), csp_constraint_create(), csp_constraint_destroy(), csp_constraint_get_arity(), csp_constraint_get_check(), csp_constraint_get_variable(), csp_constraint_set_variable(), csp_constraint_to_check(), csp_forward_check_context_create(), csp_forward_check_context_destroy(), csp_problem_backtrack(), csp_problem_create(), csp_problem_destroy(), csp_problem_get_constraint(), csp_problem_get_domain(), csp_problem_get_num_constraints(), csp_problem_get_num_domains(), csp_problem_is_consistent(), csp_problem_set_constraint(), csp_problem_set_domain(), csp_problem_solve(), csp_problem_solve_forward_checking(), and main().
csp_problem_backtrack()
bool csp_problem_backtrack (const CSPProblem * csp, size_t * values, const void * data, size_t index) extern
Recursively solves the CSP problem using backtracking from a given variable.
This function implements the core backtracking algorithm for constraint satisfaction. It attempts to assign a value to the variable at the specified index and proceeds recursively until a complete solution is found or all possibilities are exhausted.
Parameters
csp The CSP problem to solve.
values Array to store the assignments of values to variables.
data User-provided data to pass to constraint check functions.
index The index of the variable to assign next.
Returns
true if a solution is found, false if no solution exists.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
values must not be NULL.
Postcondition
If a solution is found, values contains the solution assignments.
Definition at line 297 of file csp.c.
References csp_initialised(), csp_problem_backtrack(), csp_problem_is_consistent(), _CSPProblem::domains, and _CSPProblem::num_domains.
Referenced by csp_problem_backtrack(), csp_problem_solve(), and main().
csp_problem_create()
CSPProblem * csp_problem_create (size_t num_domains, size_t num_constraints) extern
Creates a new CSP problem instance with the specified parameters.
A CSP problem consists of variables, their domains (possible values), and constraints between these variables. This function allocates memory for a new CSP problem with the specified number of variables (domains) and constraints.
Parameters
num_domains The number of variables in the CSP problem.
num_constraints The number of constraints in the CSP problem.
Returns
A new CSP problem instance, or NULL if memory allocation failed.
Precondition
The CSP library must be initialized via csp_init().
num_domains must be greater than 0.
num_constraints can be 0 for testing purposes, although typically CSPs have at least one constraint.
Postcondition
Each variable's domain size is initialized to 0.
Each constraint slot is initialized to NULL.
The CSP problem has the specified number of domains and constraints.
Definition at line 149 of file csp.c.
References _CSPProblem::constraints, csp_initialised(), _CSPProblem::domains, _CSPProblem::num_constraints, and _CSPProblem::num_domains.
Referenced by create_sudoku_problem(), main(), main(), test_context_create_destroy(), test_lcv_basic(), test_prune_neighbors(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
csp_problem_destroy()
void csp_problem_destroy (CSPProblem * csp) extern
Destroys a CSP problem instance and frees all associated resources.
This function deallocates the memory used by the CSP problem, including its domains and constraint arrays. It does not destroy the constraint objects themselves, as these are supposed to be managed by the caller.
Parameters
csp The CSP problem to destroy.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
Postcondition
All memory directly owned by the CSP problem is freed.
Definition at line 204 of file csp.c.
References _CSPProblem::constraints, csp_constraint_destroy(), csp_initialised(), _CSPProblem::domains, _CSPProblem::num_constraints, and _CSPProblem::num_domains.
Referenced by create_sudoku_problem(), main(), main(), main(), test_context_create_destroy(), test_lcv_basic(), test_prune_neighbors(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
csp_problem_get_constraint()
CSPConstraint * csp_problem_get_constraint (const CSPProblem * csp, size_t index) extern
Gets the constraint at the specified position in the CSP problem.
Parameters
csp The CSP problem to query.
index The position in the constraint array (0 to num_constraints-1).
Returns
The constraint object at the specified position, or NULL if no constraint is set.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
index must be less than the number of constraints in the CSP problem.
Definition at line 243 of file csp.c.
References _CSPProblem::constraints, and csp_initialised().
Referenced by csp_forward_check_context_create(), fc_is_consistent(), main(), main(), order_values_lcv(), and prune_neighbors().
csp_problem_get_domain()
size_t csp_problem_get_domain (const CSPProblem * csp, size_t index) extern
Gets the domain size for a variable in the CSP problem.
This function retrieves the number of possible values that can be assigned to a specific variable in the CSP problem.
Parameters
csp The CSP problem to query.
index The variable index (0 to num_domains-1).
Returns
The size of the domain for the specified variable.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
index must be less than the number of domains in the CSP problem.
Definition at line 260 of file csp.c.
References csp_initialised(), and _CSPProblem::domains.
Referenced by csp_forward_check_context_create(), main(), and main().
csp_problem_get_num_constraints()
size_t csp_problem_get_num_constraints (const CSPProblem * csp) extern
Gets the number of constraints in the CSP problem.
Constraints define relationships between variables that must be satisfied for a valid solution.
Parameters
csp The CSP problem to query.
Returns
The total number of constraints in the problem.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
Definition at line 221 of file csp.c.
References csp_initialised(), and _CSPProblem::num_constraints.
Referenced by csp_forward_check_context_create(), fc_is_consistent(), main(), main(), order_values_lcv(), and prune_neighbors().
csp_problem_get_num_domains()
size_t csp_problem_get_num_domains (const CSPProblem * csp) extern
Gets the number of variables (domains) in the CSP problem.
In this CSP implementation, each variable has a domain of possible values it can take. The size of this domain is stored separately with each variable.
Parameters
csp The CSP problem to query.
Returns
The total number of variables in the problem.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
Definition at line 249 of file csp.c.
References csp_initialised(), and _CSPProblem::num_domains.
Referenced by csp_forward_check_context_create(), main(), and main().
csp_problem_is_consistent()
bool csp_problem_is_consistent (const CSPProblem * csp, const size_t * values, const void * data, size_t index) extern
Checks if the current partial assignment is consistent with all constraints.
During the solving process, this function verifies whether the current assignment of values to variables (up to the given index) satisfies all applicable constraints. Only constraints whose variables have all been assigned are checked.
Parameters
csp The CSP problem to verify.
values The current assignment of values to variables.
data User-provided data to pass to constraint check functions.
index The index of the next variable to be assigned (all variables before this index are considered to be already assigned).
Returns
true if the current partial assignment is consistent with all applicable constraints, false otherwise.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
values must not be NULL.
Definition at line 266 of file csp.c.
References _CSPConstraint::check, _CSPProblem::constraints, csp_constraint_to_check(), csp_initialised(), and _CSPProblem::num_constraints.
Referenced by csp_problem_backtrack(), and main().
csp_problem_set_constraint()
void csp_problem_set_constraint (CSPProblem * csp, size_t index, CSPConstraint * constraint) extern
Sets a constraint at the specified position in the CSP problem.
This function assigns a constraint object to a specific position in the CSP problem's constraint array. The function performs validation to ensure that all variables referenced by the constraint exist in the CSP problem.
Parameters
csp The CSP problem to modify.
index The position in the constraint array (0 to num_constraints-1).
constraint The constraint object to assign.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
index must be less than the number of constraints in the CSP problem.
constraint must not be NULL.
All variables in the constraint must have indices less than csp->num_domains.
Postcondition
The constraint at the specified index is set to the provided constraint object.
Definition at line 226 of file csp.c.
References _CSPConstraint::arity, _CSPProblem::constraints, csp_initialised(), _CSPProblem::num_domains, and _CSPConstraint::variables.
Referenced by create_sudoku_problem(), main(), main(), test_lcv_basic(), test_prune_neighbors(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
csp_problem_set_domain()
void csp_problem_set_domain (CSPProblem * csp, size_t index, size_t domain) extern
Sets the domain size for a variable in the CSP problem.
This function specifies how many possible values a given variable can take. For example, if a variable can be assigned values from 0 to 9, its domain size would be 10. The actual values are assumed to be 0, 1, 2, ..., domain-1.
Parameters
csp The CSP problem to modify.
index The variable index (0 to num_domains-1).
domain The size of the domain (number of possible values) for this variable.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
index must be less than the number of domains in the CSP problem.
Postcondition
The domain size for the specified variable is set to the provided value.
Definition at line 254 of file csp.c.
References csp_initialised(), and _CSPProblem::domains.
Referenced by create_sudoku_problem(), main(), main(), test_context_create_destroy(), test_lcv_basic(), test_prune_neighbors(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
csp_problem_solve()
bool csp_problem_solve (const CSPProblem * csp, size_t * values, const void * data) extern
Solves a CSP problem using the basic backtracking algorithm.
This is a convenience function that initiates the backtracking process from the beginning (first variable). It's the main entry point for solving a CSP problem with the basic backtracking algorithm.
Parameters
csp The CSP problem to solve.
values Array to store the assignments of values to variables.
data User-provided data to pass to constraint check functions.
Returns
true if a solution is found, false if no solution exists.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
values must not be NULL.
Postcondition
If a solution is found, values contains the solution assignments.
Definition at line 292 of file csp.c.
References csp_initialised(), and csp_problem_backtrack().