CSP-lib: Constraint Satisfaction Problem Solver Library: src/forward-checking.c File Reference
forward-checking.c File Reference
Forward checking algorithm with MRV and LCV heuristics implementation.
#include "forward-checking.h"
#include <assert.h>
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include "csp_internal.h"
#include "heuristics.h"
Functions
static bool backtrack_fc (const CSPProblem *csp, size_t *values, const void *data, CSPForwardCheckContext *ctx)
CSPForwardCheckContext * csp_forward_check_context_create (const CSPProblem *csp)
Creates and initializes a forward checking context.
void csp_forward_check_context_destroy (CSPForwardCheckContext *ctx)
Destroys a forward checking context and frees all associated memory.
bool csp_problem_solve_forward_checking (const CSPProblem *csp, size_t *values, const void *data)
Solves a CSP problem using the forward checking algorithm with heuristics.
static bool fc_is_consistent (const CSPProblem *csp, const size_t *values, const void *data, const CSPForwardCheckContext *ctx)
Checks consistency of the current assignment under forward checking.
Variables
volatile sig_atomic_t timeout_occurred = 0
Recursive backtracking function with forward checking.
Detailed Description
Forward checking algorithm with MRV and LCV heuristics implementation.
This module implements a CSP solver that uses forward checking to prune domains as soon as a variable is assigned, combined with two heuristics:
Minimum Remaining Values (MRV) for variable ordering
Least Constraining Value (LCV) for value ordering
Forward checking reduces search space by removing inconsistent values early, and the heuristics guide the search toward a solution efficiently.
Definition in file forward-checking.c.
Function Documentation
backtrack_fc()
static bool backtrack_fc (const CSPProblem * csp, size_t * values, const void * data, CSPForwardCheckContext * ctx) static
Definition at line 81 of file forward-checking.c.
References _CSPForwardCheckContext::assigned, backtrack_fc(), csp_initialised(), fc_is_consistent(), _CSPForwardCheckContext::num_domains, order_values_lcv(), _CSPForwardCheckContext::original_domain_sizes, prune_neighbors(), restore_pruned(), select_unassigned_var(), and timeout_occurred.
Referenced by backtrack_fc(), and csp_problem_solve_forward_checking().
csp_forward_check_context_create()
CSPForwardCheckContext * csp_forward_check_context_create (const CSPProblem * csp)
Creates and initializes a forward checking context.
Creates a forward checking context for the given CSP problem.
This function allocates and initializes all the data structures needed for the forward checking algorithm:
The original domain sizes for each variable
The current available values for each variable (initially all values are available)
The assignment status for each variable (initially all are unassigned)
The context is crucial for implementing both the MRV and LCV heuristics as well as for tracking domain pruning during forward checking.
Parameters
csp The CSP problem for which to create a context.
Returns
A newly created forward checking context, or NULL if memory allocation failed.
Definition at line 194 of file forward-checking.c.
References _CSPForwardCheckContext::assigned, csp_constraint_get_arity(), csp_constraint_get_check(), csp_constraint_get_variable(), csp_initialised(), csp_problem_get_constraint(), csp_problem_get_domain(), csp_problem_get_num_constraints(), csp_problem_get_num_domains(), _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by csp_problem_solve_forward_checking(), test_context_create_destroy(), test_lcv_basic(), and test_prune_neighbors().
csp_forward_check_context_destroy()
void csp_forward_check_context_destroy (CSPForwardCheckContext * ctx)
Destroys a forward checking context and frees all associated memory.
Destroys a forward checking context and frees all associated resources.
This function properly deallocates all resources used by a forward checking context:
The arrays tracking available values for each domain
The array of original domain sizes
The array tracking variable assignments
The context structure itself
The function safely handles NULL contexts by doing nothing.
Parameters
ctx The forward checking context to destroy.
Definition at line 290 of file forward-checking.c.
References _CSPForwardCheckContext::assigned, csp_initialised(), _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by csp_problem_solve_forward_checking(), test_context_create_destroy(), test_lcv_basic(), and test_prune_neighbors().
csp_problem_solve_forward_checking()
bool csp_problem_solve_forward_checking (const CSPProblem * csp, size_t * values, const void * data)
Solves a CSP problem using the forward checking algorithm with heuristics.
This function serves as the main entry point for solving a CSP using forward checking. It performs the following steps:
Creates a forward checking context for the problem
Calls the recursive backtracking function to find a solution
Destroys the context after solving (regardless of whether a solution was found)
Returns whether a solution was found
The forward checking algorithm with MRV and LCV heuristics typically performs much better than basic backtracking, especially for larger or more constrained problems.
Parameters
csp The CSP problem to solve.
values Array to store the assignments of values to variables.
data User-provided data for constraint checking.
Returns
true if a solution is found, false otherwise.
Definition at line 328 of file forward-checking.c.
References backtrack_fc(), csp_forward_check_context_create(), csp_forward_check_context_destroy(), and csp_initialised().
Referenced by main(), main(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
fc_is_consistent()
static bool fc_is_consistent (const CSPProblem * csp, const size_t * values, const void * data, const CSPForwardCheckContext * ctx) static
Checks consistency of the current assignment under forward checking.
Only constraints whose all variables have already been assigned (according to ctx->assigned) are tested. Unassigned variables are ignored, avoiding false conflicts on default values.
Definition at line 21 of file forward-checking.c.
References _CSPForwardCheckContext::assigned, csp_constraint_get_arity(), csp_constraint_get_check(), csp_constraint_get_variable(), csp_problem_get_constraint(), and csp_problem_get_num_constraints().
Referenced by backtrack_fc().
Variable Documentation
timeout_occurred
volatile sig_atomic_t timeout_occurred = 0
Recursive backtracking function with forward checking.
This function implements the core of the forward checking algorithm:
Check if all variables are assigned - if so, return success
Select the next unassigned variable using the MRV heuristic
Order the values for this variable using the LCV heuristic
Try each value in order: a. Assign the value to the variable b. Check if the assignment is consistent c. Prune inconsistent values from future variables d. Recursively try to assign the remaining variables e. If successful, return the solution f. If unsuccessful, restore pruned values and try the next value
Parameters
csp The CSP problem to solve.
values Array to store the assignments of values to variables.
data User-provided data for constraint checking.
ctx The forward checking context.
Returns
true if a solution is found, false otherwise.
Definition at line 13 of file forward-checking.c.
Referenced by backtrack_fc(), handle_timeout(), and main().