CSP-lib: Constraint Satisfaction Problem Solver Library: src/forward-checking.h File Reference
forward-checking.h File Reference
Forward checking algorithm for constraint satisfaction problems.
#include "csp.h"
Data Structures
struct _CSPForwardCheckContext
Typedefs
typedef struct _CSPForwardCheckContext CSPForwardCheckContext
Functions
CSPForwardCheckContext * csp_forward_check_context_create (const CSPProblem *csp)
Creates a forward checking context for the given CSP problem.
void csp_forward_check_context_destroy (CSPForwardCheckContext *context)
Destroys a forward checking context and frees all associated resources.
bool csp_problem_solve_forward_checking (const CSPProblem *csp, size_t *values, const void *data)
Solves a CSP problem using the forward checking algorithm with heuristics.
Detailed Description
Forward checking algorithm for constraint satisfaction problems.
This file provides an implementation of the forward checking algorithm for solving constraint satisfaction problems. Forward checking is an improvement over basic backtracking that prunes inconsistent values from variable domains as soon as a variable assignment is made.
The Forward Checking Algorithm
Forward checking works by:
Assigning a value to a variable
Immediately checking all constraints involving that variable and unassigned variables
Temporarily removing inconsistent values from the domains of unassigned variables
If any domain becomes empty, backtracking immediately
When backtracking, restoring previously pruned domain values
This approach helps detect failures earlier than naive backtracking, avoiding unnecessary exploration of dead-end paths in the search space.
Integrated Heuristics
The implementation incorporates two key heuristics:
Minimum Remaining Values (MRV): Prioritizes variables with the fewest valid values in their domain, focusing search on the most constrained variables first.
Least Constraining Value (LCV): Prioritizes values that eliminate the fewest options for neighboring variables, maximizing flexibility for future assignments.
Example Usage
// Create a CSP problem
CSPProblem *problem = create_my_csp_problem();
// Array to store the solution
size_t solution[NUM_VARS];
// Solve using forward checking
bool solved = solve_with_forward_checking(problem, solution, NULL, NULL);
if (solved) {
    // Process solution
} else {
    // No solution exists
}
Author
Ch. Demko (original)
Date
2024-2025
Version
1.0
Definition in file forward-checking.h.
Typedef Documentation
CSPForwardCheckContext
typedef struct _CSPForwardCheckContext CSPForwardCheckContext
Function Documentation
csp_forward_check_context_create()
CSPForwardCheckContext * csp_forward_check_context_create (const CSPProblem * csp) extern
Creates a forward checking context for the given CSP problem.
This function initializes a new context for the forward checking algorithm based on the provided CSP problem. It allocates memory for tracking:
Original domain sizes
Current available domain values
Variable assignment status
Initially, all domain values are marked as available, and no variables are assigned.
Parameters
csp The CSP problem for which to create a forward checking context.
Returns
A new forward checking context, or NULL if memory allocation failed.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
Postcondition
If successful, returns a fully initialized context with all domains marked as fully available.
If memory allocation fails at any stage, all already allocated memory is freed and NULL is returned.
Creates a forward checking context for the given CSP problem.
This function allocates and initializes all the data structures needed for the forward checking algorithm:
The original domain sizes for each variable
The current available values for each variable (initially all values are available)
The assignment status for each variable (initially all are unassigned)
The context is crucial for implementing both the MRV and LCV heuristics as well as for tracking domain pruning during forward checking.
Parameters
csp The CSP problem for which to create a context.
Returns
A newly created forward checking context, or NULL if memory allocation failed.
Definition at line 194 of file forward-checking.c.
References _CSPForwardCheckContext::assigned, csp_constraint_get_arity(), csp_constraint_get_check(), csp_constraint_get_variable(), csp_initialised(), csp_problem_get_constraint(), csp_problem_get_domain(), csp_problem_get_num_constraints(), csp_problem_get_num_domains(), _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by csp_problem_solve_forward_checking(), test_context_create_destroy(), test_lcv_basic(), and test_prune_neighbors().
csp_forward_check_context_destroy()
void csp_forward_check_context_destroy (CSPForwardCheckContext * ctx) extern
Destroys a forward checking context and frees all associated resources.
This function deallocates all memory used by the forward checking context, including domain availability arrays and other internal state.
Parameters
context The forward checking context to destroy.
Precondition
The CSP library must be initialized via csp_init().
context can be NULL (in which case the function does nothing).
Postcondition
All memory associated with the context is freed.
Destroys a forward checking context and frees all associated resources.
This function properly deallocates all resources used by a forward checking context:
The arrays tracking available values for each domain
The array of original domain sizes
The array tracking variable assignments
The context structure itself
The function safely handles NULL contexts by doing nothing.
Parameters
ctx The forward checking context to destroy.
Definition at line 290 of file forward-checking.c.
References _CSPForwardCheckContext::assigned, csp_initialised(), _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by csp_problem_solve_forward_checking(), test_context_create_destroy(), test_lcv_basic(), and test_prune_neighbors().
csp_problem_solve_forward_checking()
bool csp_problem_solve_forward_checking (const CSPProblem * csp, size_t * values, const void * data) extern
Solves a CSP problem using the forward checking algorithm with heuristics.
This function implements the forward checking algorithm, which is an improvement over basic backtracking. Forward checking works by immediately pruning from the domains of future variables any values that would violate a constraint with the current assignment.
This implementation also incorporates two powerful heuristics:
Minimum Remaining Values (MRV): Selects the variable with the fewest remaining valid values in its domain, which helps identify bottlenecks early.
Least Constraining Value (LCV): Orders values for a variable by how many options they eliminate from the domains of neighboring variables, trying values that constrain neighbors the least first.
Parameters
csp The CSP problem to solve.
values Array to store the assignments of values to variables.
data User-provided data to pass to constraint check functions.
Returns
true if a solution is found, false if no solution exists.
Precondition
The CSP library must be initialized via csp_init().
csp must not be NULL.
values must not be NULL and must be large enough to hold assignments for all variables.
Postcondition
If a solution is found, values contains the solution assignments.
This function serves as the main entry point for solving a CSP using forward checking. It performs the following steps:
Creates a forward checking context for the problem
Calls the recursive backtracking function to find a solution
Destroys the context after solving (regardless of whether a solution was found)
Returns whether a solution was found
The forward checking algorithm with MRV and LCV heuristics typically performs much better than basic backtracking, especially for larger or more constrained problems.
Parameters
csp The CSP problem to solve.
values Array to store the assignments of values to variables.
data User-provided data for constraint checking.
Returns
true if a solution is found, false otherwise.
Definition at line 328 of file forward-checking.c.
References backtrack_fc(), csp_forward_check_context_create(), csp_forward_check_context_destroy(), and csp_initialised().
Referenced by main(), main(), test_single_var(), test_solve_simple(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().