CSP-lib: Constraint Satisfaction Problem Solver Library: src/heuristics.c File Reference
heuristics.c File Reference
Implementation of heuristics for improving CSP solver performance.
#include "heuristics.h"
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include "csp_internal.h"
Functions
void order_values_lcv (const CSPProblem *csp, CSPForwardCheckContext *ctx, const size_t *values, const void *data, size_t var, size_t *ordered, size_t *n_vals)
Implements the Least Constraining Value (LCV) heuristic for value ordering.
void prune_neighbors (const CSPProblem *csp, const size_t *values, const void *data, CSPForwardCheckContext *ctx, size_t var, size_t *counts, size_t **pruned)
Prunes inconsistent values from neighboring variables during forward checking.
void restore_pruned (CSPForwardCheckContext *ctx, const size_t *counts, size_t **pruned)
Restores values that were pruned during forward checking when backtracking occurs.
size_t select_unassigned_var (const CSPForwardCheckContext *ctx)
Implements the Minimum Remaining Values (MRV) heuristic for variable selection.
Detailed Description
Implementation of heuristics for improving CSP solver performance.
This file implements various heuristics used in constraint satisfaction problem solving:
Minimum Remaining Values (MRV): For variable selection
Least Constraining Value (LCV): For value ordering
Domain pruning mechanisms for forward checking
Restoration of pruned domains during backtracking
These heuristics significantly improve the efficiency of the solving process by making intelligent choices that reduce the search space.
Author
Ch. Demko (original)
Date
2024-2025
Version
1.0
Definition in file heuristics.c.
Function Documentation
order_values_lcv()
void order_values_lcv (const CSPProblem * csp, CSPForwardCheckContext * ctx, const size_t * values, const void * data, size_t var, size_t * ordered, size_t * n_vals)
Implements the Least Constraining Value (LCV) heuristic for value ordering.
Orders values for a given variable using the LCV (Least Constraining Value) heuristic.
This function orders the values in a variable's domain by how constraining they are on the domains of neighboring variables (those connected by constraints).
For each possible value in the domain:
It counts how many values would become invalid in neighboring variables if this value is chosen
It sorts the values from least constraining (fewest conflicts) to most constraining
This heuristic increases the likelihood of finding a valid assignment without backtracking by trying the values that leave the most flexibility for future assignments first.
The implementation:
Only considers binary constraints (between exactly 2 variables)
Uses a simple insertion sort to order the values
Temporarily modifies the values array for checking (but restores it)
Parameters
csp The CSP problem.
ctx The forward checking context.
values The current assignment of values to variables.
data User-provided data for constraint checking.
var The variable for which to order values.
ordered Output array where ordered values will be stored.
n_vals Output parameter that will be set to the number of valid values.
Definition at line 98 of file heuristics.c.
References _CSPForwardCheckContext::assigned, _CSPConstraint::check, csp_constraint_get_arity(), csp_constraint_get_variable(), csp_problem_get_constraint(), csp_problem_get_num_constraints(), _CSPForwardCheckContext::current_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by backtrack_fc(), and test_lcv_basic().
prune_neighbors()
void prune_neighbors (const CSPProblem * csp, const size_t * values, const void * data, CSPForwardCheckContext * ctx, size_t var, size_t * counts, size_t ** pruned)
Prunes inconsistent values from neighboring variables during forward checking.
Prunes inconsistent values from neighboring variables after an assignment.
This function is the core of the forward checking algorithm. After a variable is assigned a value, this function examines all neighboring variables (those connected by constraints) and removes any values from their domains that would violate a constraint, given the current assignment.
For each binary constraint involving the assigned variable:
It identifies the other variable in the constraint
It checks each value in that variable's domain
If a value would violate the constraint with the current assignment, it's marked as unavailable
The pruned value is recorded so it can be restored if we need to backtrack
The pruned values are tracked in two data structures:
counts[v] records how many values were pruned from variable v
pruned[v] stores which values were pruned from variable v
Parameters
csp The CSP problem.
values The current assignment of values to variables.
data User-provided data for constraint checking.
ctx The forward checking context to update.
var The variable that was just assigned.
counts Array to record the number of pruned values for each variable.
pruned 2D array to record which values were pruned from each variable.
Definition at line 234 of file heuristics.c.
References _CSPForwardCheckContext::assigned, csp_constraint_get_arity(), csp_constraint_get_check(), csp_constraint_get_variable(), csp_problem_get_constraint(), csp_problem_get_num_constraints(), _CSPForwardCheckContext::current_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by backtrack_fc(), and test_prune_neighbors().
restore_pruned()
void restore_pruned (CSPForwardCheckContext * ctx, const size_t * counts, size_t ** pruned)
Restores values that were pruned during forward checking when backtracking occurs.
Restores previously pruned values when backtracking.
When the solving algorithm needs to backtrack (because it reached a dead end), this function restores all the domain values that were pruned as a result of the assignment that's being undone. This ensures that the search can continue with different value assignments.
For each variable:
It examines the list of values that were pruned from that variable
It marks each of these values as available again in the current domains
It frees the memory used to track pruned values
This function is essential for the completeness of the backtracking algorithm, ensuring that no potential solutions are missed.
Parameters
ctx The forward checking context to update.
counts Array indicating how many values were pruned for each variable.
pruned 2D array indicating which values were pruned from each variable.
Definition at line 311 of file heuristics.c.
References _CSPForwardCheckContext::current_domains, and _CSPForwardCheckContext::num_domains.
Referenced by backtrack_fc(), test_prune_neighbors(), and test_restore_pruned().
select_unassigned_var()
size_t select_unassigned_var (const CSPForwardCheckContext * ctx)
Implements the Minimum Remaining Values (MRV) heuristic for variable selection.
Selects the next unassigned variable using the MRV (Minimum Remaining Values) heuristic.
This function examines all unassigned variables and selects the one with the fewest remaining legal values in its domain. This heuristic aims to identify the most constrained variable, which is most likely to cause a failure if left for later (the "fail-first" principle).
If multiple variables have the same minimum number of remaining values, the first one encountered is returned.
Parameters
ctx The forward checking context containing domain information.
Returns
The index of the unassigned variable with the fewest remaining legal values.
Definition at line 42 of file heuristics.c.
References _CSPForwardCheckContext::assigned, _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by backtrack_fc(), test_mrv_simple(), and test_mrv_skip_assigned().