CSP-lib: Constraint Satisfaction Problem Solver Library: src/heuristics.h File Reference
heuristics.h File Reference
Heuristics for improving CSP solver performance.
#include <stddef.h>
#include "forward-checking.h"
Functions
void order_values_lcv (const CSPProblem *csp, CSPForwardCheckContext *ctx, const size_t *values, const void *data, size_t var, size_t *ordered, size_t *n_vals)
Orders values for a given variable using the LCV (Least Constraining Value) heuristic.
void prune_neighbors (const CSPProblem *csp, const size_t *values, const void *data, CSPForwardCheckContext *ctx, size_t var, size_t *counts, size_t **pruned)
Prunes inconsistent values from neighboring variables after an assignment.
void restore_pruned (CSPForwardCheckContext *ctx, const size_t *counts, size_t **pruned)
Restores previously pruned values when backtracking.
size_t select_unassigned_var (const CSPForwardCheckContext *ctx)
Selects the next unassigned variable using the MRV (Minimum Remaining Values) heuristic.
Detailed Description
Heuristics for improving CSP solver performance.
This file provides implementations of common heuristics used to improve the efficiency of constraint satisfaction problem (CSP) solvers. These heuristics help guide the search process by making intelligent choices about:
Which variable to assign next (variable ordering)
Which value to try first for a variable (value ordering)
How to prune impossible values during forward checking
How to restore pruned values during backtracking
Overview of CSP Heuristics
Heuristics are essential for making CSP solvers efficient in practice. Without good heuristics, even moderately sized problems can become computationally intractable. The heuristics in this library focus on:
Variable Ordering
Minimum Remaining Values (MRV): Also known as "fail-first" heuristic, this selects the variable with the fewest remaining legal values in its domain. The intuition is that if a variable has few legal values, it's more likely to cause a failure soon, which allows the solver to backtrack earlier rather than later.
MRV Heuristic: Choose variable with fewest remaining values
Value Ordering
Least Constraining Value (LCV): This heuristic chooses the value that rules out the fewest choices for neighboring variables. The intuition is to maximize the flexibility for subsequent variable assignments, increasing the likelihood of finding a solution without backtracking.
LCV Heuristic: Choose value that constrains neighbors least
Domain Pruning
Forward Checking: While not strictly a heuristic, this approach works alongside the variable and value ordering heuristics. It prunes domain values that would violate constraints given the current assignment, which enables early detection of dead ends.
Performance Impact
Properly implemented heuristics can dramatically improve solving performance:
Reduce search space exploration by orders of magnitude
Allow solving of much larger problems
Convert exponential-time searches to near-linear in many practical cases
Usage
The heuristics are integrated directly into the forward checking algorithm and can be used by simply calling the forward checking solver:
// Using MRV and LCV heuristics by default
solve_with_forward_checking(problem, solution, NULL, NULL);
// To use custom heuristic functions
solve_with_forward_checking(problem, solution, custom_select_var, custom_order_values);
Author
Ch. Demko (original)
Date
2024-2025
Version
1.0
See also
solve_with_forward_checking()
select_unassigned_variable_mrv()
order_domain_values_lcv()
Definition in file heuristics.h.
Function Documentation
order_values_lcv()
void order_values_lcv (const CSPProblem * csp, CSPForwardCheckContext * ctx, const size_t * values, const void * data, size_t var, size_t * ordered, size_t * n_vals) extern
Orders values for a given variable using the LCV (Least Constraining Value) heuristic.
The LCV heuristic chooses values in order of how many options they rule out for neighboring variables. The values that eliminate the fewest options for neighbors are tried first. This increases the likelihood of finding a valid assignment without having to backtrack.
This function counts "conflicts" - the number of values in neighboring variables that would be ruled out by each possible value assignment - and sorts values from least constraining (fewest conflicts) to most constraining (most conflicts).
Parameters
csp The CSP problem instance.
ctx The forward checking context.
values The current assignment of values to variables.
data User-provided data for constraint checking.
var The variable for which to order values.
ordered Output array where ordered values will be stored.
n_vals Output parameter that will be set to the number of valid values.
Precondition
csp, ctx, values, ordered, and n_vals must not be NULL.
var must be a valid variable index in the CSP.
ordered must have enough space to hold all possible values for the variable.
Postcondition
ordered[0..(*n_vals-1)] contains the values in the domain of var ordered by the LCV heuristic.
*n_vals is set to the number of valid values in the domain of var.
Orders values for a given variable using the LCV (Least Constraining Value) heuristic.
This function orders the values in a variable's domain by how constraining they are on the domains of neighboring variables (those connected by constraints).
For each possible value in the domain:
It counts how many values would become invalid in neighboring variables if this value is chosen
It sorts the values from least constraining (fewest conflicts) to most constraining
This heuristic increases the likelihood of finding a valid assignment without backtracking by trying the values that leave the most flexibility for future assignments first.
The implementation:
Only considers binary constraints (between exactly 2 variables)
Uses a simple insertion sort to order the values
Temporarily modifies the values array for checking (but restores it)
Parameters
csp The CSP problem.
ctx The forward checking context.
values The current assignment of values to variables.
data User-provided data for constraint checking.
var The variable for which to order values.
ordered Output array where ordered values will be stored.
n_vals Output parameter that will be set to the number of valid values.
Definition at line 98 of file heuristics.c.
References _CSPForwardCheckContext::assigned, _CSPConstraint::check, csp_constraint_get_arity(), csp_constraint_get_variable(), csp_problem_get_constraint(), csp_problem_get_num_constraints(), _CSPForwardCheckContext::current_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by backtrack_fc(), and test_lcv_basic().
prune_neighbors()
void prune_neighbors (const CSPProblem * csp, const size_t * values, const void * data, CSPForwardCheckContext * ctx, size_t var, size_t * counts, size_t ** pruned) extern
Prunes inconsistent values from neighboring variables after an assignment.
This function is a key component of the forward checking algorithm. After assigning a value to a variable, this function checks all neighboring variables (those that share a constraint with the assigned variable) and removes any values that would violate a constraint with the current assignment.
The pruned values are recorded so they can be restored if backtracking becomes necessary.
Parameters
csp The CSP problem instance.
values The current assignment of values to variables.
data User-provided data for constraint checking.
ctx The forward checking context to update.
var The variable that was just assigned.
counts Array to record the number of pruned values for each variable.
pruned 2D array to record which values were pruned from each variable.
Precondition
csp, values, ctx, counts, and pruned must not be NULL.
var must be a valid variable index in the CSP.
counts must be an array of size ctx->num_domains, initialized to zeros.
pruned must be an array of size ctx->num_domains, initialized to NULL.
Postcondition
Domain values that would violate constraints with the current assignment are marked as unavailable.
counts[i] records the number of values pruned from variable i.
pruned[i] records which values were pruned from variable i.
Prunes inconsistent values from neighboring variables after an assignment.
This function is the core of the forward checking algorithm. After a variable is assigned a value, this function examines all neighboring variables (those connected by constraints) and removes any values from their domains that would violate a constraint, given the current assignment.
For each binary constraint involving the assigned variable:
It identifies the other variable in the constraint
It checks each value in that variable's domain
If a value would violate the constraint with the current assignment, it's marked as unavailable
The pruned value is recorded so it can be restored if we need to backtrack
The pruned values are tracked in two data structures:
counts[v] records how many values were pruned from variable v
pruned[v] stores which values were pruned from variable v
Parameters
csp The CSP problem.
values The current assignment of values to variables.
data User-provided data for constraint checking.
ctx The forward checking context to update.
var The variable that was just assigned.
counts Array to record the number of pruned values for each variable.
pruned 2D array to record which values were pruned from each variable.
Definition at line 234 of file heuristics.c.
References _CSPForwardCheckContext::assigned, csp_constraint_get_arity(), csp_constraint_get_check(), csp_constraint_get_variable(), csp_problem_get_constraint(), csp_problem_get_num_constraints(), _CSPForwardCheckContext::current_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by backtrack_fc(), and test_prune_neighbors().
restore_pruned()
void restore_pruned (CSPForwardCheckContext * ctx, const size_t * counts, size_t ** pruned) extern
Restores previously pruned values when backtracking.
When backtracking occurs (due to encountering a dead end in the search), this function restores all the domain values that were previously pruned during forward checking. This ensures that the search can continue correctly with different assignments.
Parameters
ctx The forward checking context to update.
counts Array indicating how many values were pruned for each variable.
pruned 2D array indicating which values were pruned from each variable.
Precondition
ctx, counts, and pruned must not be NULL.
pruned[i] must either be NULL or point to an array recording which values were pruned from variable i.
Postcondition
All pruned values are restored (marked as available again).
Memory allocated for the pruned arrays is freed.
Restores previously pruned values when backtracking.
When the solving algorithm needs to backtrack (because it reached a dead end), this function restores all the domain values that were pruned as a result of the assignment that's being undone. This ensures that the search can continue with different value assignments.
For each variable:
It examines the list of values that were pruned from that variable
It marks each of these values as available again in the current domains
It frees the memory used to track pruned values
This function is essential for the completeness of the backtracking algorithm, ensuring that no potential solutions are missed.
Parameters
ctx The forward checking context to update.
counts Array indicating how many values were pruned for each variable.
pruned 2D array indicating which values were pruned from each variable.
Definition at line 311 of file heuristics.c.
References _CSPForwardCheckContext::current_domains, and _CSPForwardCheckContext::num_domains.
Referenced by backtrack_fc(), test_prune_neighbors(), and test_restore_pruned().
select_unassigned_var()
size_t select_unassigned_var (const CSPForwardCheckContext * ctx) extern
Selects the next unassigned variable using the MRV (Minimum Remaining Values) heuristic.
The MRV heuristic chooses the variable with the fewest remaining legal values in its domain. This is often referred to as the "most constrained variable" or "fail-first" heuristic, as it tends to identify variables that are most likely to cause a failure quickly, helping to prune the search tree more effectively.
Parameters
ctx The forward checking context containing domain and assignment information.
Returns
The index of the unassigned variable with the fewest remaining legal values.
Precondition
ctx must not be NULL.
ctx must contain at least one unassigned variable.
Selects the next unassigned variable using the MRV (Minimum Remaining Values) heuristic.
This function examines all unassigned variables and selects the one with the fewest remaining legal values in its domain. This heuristic aims to identify the most constrained variable, which is most likely to cause a failure if left for later (the "fail-first" principle).
If multiple variables have the same minimum number of remaining values, the first one encountered is returned.
Parameters
ctx The forward checking context containing domain information.
Returns
The index of the unassigned variable with the fewest remaining legal values.
Definition at line 42 of file heuristics.c.
References _CSPForwardCheckContext::assigned, _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by backtrack_fc(), test_mrv_simple(), and test_mrv_skip_assigned().