CSP-lib: Constraint Satisfaction Problem Solver Library: src/solve-sudoku.c File Reference
solve-sudoku.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "csp.h"
#include "forward-checking.h"
Macros
#define SUDOKU_CELLS 81
#define SUDOKU_SIZE 9
Functions
int main (int argc, char *argv[])
void print_sudoku (const size_t *solution)
Prints the solved Sudoku grid in a human-readable format.
bool read_puzzle (FILE *in)
Reads a Sudoku puzzle from stdin or file: 9 lines of 9 digits or dots.
bool sudoku_not_equal (const CSPConstraint *constraint, const size_t *values, const void *data)
Checker for binary all-different constraint.
bool sudoku_preassigned (const CSPConstraint *constraint, const size_t *values, const void *data)
Checker to enforce a cell's pre-assigned value.
Variables
static int initial_grid [SUDOKU_CELLS]
Macro Definition Documentation
SUDOKU_CELLS
#define SUDOKU_CELLS 81
Definition at line 17 of file solve-sudoku.c.
SUDOKU_SIZE
#define SUDOKU_SIZE 9
Definition at line 16 of file solve-sudoku.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 99 of file solve-sudoku.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_finish(), csp_init(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), csp_problem_solve_forward_checking(), initial_grid, print_sudoku(), read_puzzle(), SUDOKU_CELLS, sudoku_not_equal(), sudoku_preassigned(), and SUDOKU_SIZE.
print_sudoku()
void print_sudoku (const size_t * solution)
Prints the solved Sudoku grid in a human-readable format.
Definition at line 64 of file solve-sudoku.c.
References SUDOKU_SIZE.
Referenced by main().
read_puzzle()
bool read_puzzle (FILE * in)
Reads a Sudoku puzzle from stdin or file: 9 lines of 9 digits or dots.
Dot ('.') or '0' indicates blank. Digits '1'..'9' indicate pre-filled cells.
Definition at line 82 of file solve-sudoku.c.
References initial_grid, and SUDOKU_SIZE.
Referenced by main().
sudoku_not_equal()
bool sudoku_not_equal (const CSPConstraint * constraint, const size_t * values, const void * data)
Checker for binary all-different constraint.
Ensures that two variables do not have the same value.
Parameters
constraint The binary constraint object.
values Current assignment to all variables.
data Unused (NULL).
Returns
true if values differ, false if equal.
Definition at line 55 of file solve-sudoku.c.
References csp_constraint_get_variable().
Referenced by main().
sudoku_preassigned()
bool sudoku_preassigned (const CSPConstraint * constraint, const size_t * values, const void * data)
Checker to enforce a cell's pre-assigned value.
For a unary constraint, ensures that the assigned value matches the initial puzzle. If the cell was blank in the puzzle (initial_grid[var] == 0), this constraint always passes.
Parameters
constraint The unary constraint object.
values Current assignment to all variables.
data Unused (NULL).
Returns
true if cell value matches the pre-assigned value or if blank, false otherwise.
Definition at line 33 of file solve-sudoku.c.
References csp_constraint_get_variable(), and initial_grid.
Referenced by main().
Variable Documentation
initial_grid
int initial_grid[SUDOKU_CELLS] static
Definition at line 20 of file solve-sudoku.c.
Referenced by create_sudoku_problem(), main(), read_puzzle(), read_sudoku_puzzle(), sudoku_preassigned(), and sudoku_preassigned_checker().