CSP-lib: Constraint Satisfaction Problem Solver Library: src/sudoku_utils.c File Reference
sudoku_utils.c File Reference
#include "sudoku_utils.h"
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include "csp_internal.h"
Functions
CSPProblem * create_sudoku_problem (const int initial_grid[SUDOKU_CELLS])
Creates a CSP problem that models the Sudoku puzzle.
void print_sudoku_solution (const size_t solution[SUDOKU_CELLS])
Prints a solved Sudoku grid in a human-readable format.
bool read_sudoku_puzzle (FILE *in, int initial_grid[SUDOKU_CELLS])
Reads a Sudoku puzzle from the given input stream.
static bool sudoku_not_equal_checker (const CSPConstraint *constraint, const size_t *values, const void *data)
static bool sudoku_preassigned_checker (const CSPConstraint *constraint, const size_t *values, const void *data)
Function Documentation
create_sudoku_problem()
CSPProblem * create_sudoku_problem (const int initial_grid[SUDOKU_CELLS])
Creates a CSP problem that models the Sudoku puzzle.
This function converts a Sudoku puzzle into a constraint satisfaction problem by creating:
81 variables, one for each cell, with domains {0,1,...,8} (representing 1-9)
81 unary constraints for pre-filled cells (to enforce their initial values)
27 groups of binary constraints (one for each row, column, and 3x3 block)
Each group requires all cell values to be different
The resulting CSP has 1053 constraints in total:
81 unary constraints for pre-filled cells
972 binary constraints for the all-different requirements
Parameters
initial_grid Array containing the initial puzzle (0 for blank cells, 1-9 for filled)
Returns
Pointer to a newly created CSP problem, or NULL on allocation failure
Note
The caller is responsible for destroying the problem with csp_problem_destroy()
Warning
The function will return NULL if memory allocation fails
Definition at line 111 of file sudoku_utils.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), initial_grid, SUDOKU_CELLS, sudoku_not_equal_checker(), sudoku_preassigned_checker(), and SUDOKU_SIZE.
Referenced by main().
print_sudoku_solution()
void print_sudoku_solution (const size_t solution[SUDOKU_CELLS])
Prints a solved Sudoku grid in a human-readable format.
The function prints the solved Sudoku grid to standard output using a visually appealing format with:
Horizontal and vertical separators between 3x3 blocks
Cell values displayed as digits 1-9
Clear row and column alignment
Example output:
* +-------+-------+-------+
* | 5 3 4 | 6 7 8 | 9 1 2 |
* | 6 7 2 | 1 9 5 | 3 4 8 |
* | 1 9 8 | 3 4 2 | 5 6 7 |
* +-------+-------+-------+
* | 8 5 9 | 7 6 1 | 4 2 3 |
* | 4 2 6 | 8 5 3 | 7 9 1 |
* | 7 1 3 | 9 2 4 | 8 5 6 |
* +-------+-------+-------+
* | 9 6 1 | 5 3 7 | 2 8 4 |
* | 2 8 7 | 4 1 9 | 6 3 5 |
* | 3 4 5 | 2 8 6 | 1 7 9 |
* +-------+-------+-------+
*
Parameters
solution Array of assigned values (0-8 representing digits 1-9)
Note
If solution is NULL, the function returns without doing anything
Definition at line 86 of file sudoku_utils.c.
References SUDOKU_SIZE.
Referenced by main().
read_sudoku_puzzle()
bool read_sudoku_puzzle (FILE * in, int initial_grid[SUDOKU_CELLS])
Reads a Sudoku puzzle from the given input stream.
Parses a Sudoku puzzle from a text file where:
Each row is on a separate line (9 lines total)
Each cell is represented by a single character:
'1' through '9' for pre-filled cells
'.' or '0' for blank cells that need to be filled
Parameters
in File pointer to read from
initial_grid Array to store the parsed puzzle (0 for blank cells, 1-9 for filled)
Returns
true if parsing was successful, false on I/O error or invalid format
Precondition
in != NULL
initial_grid != NULL and can store at least SUDOKU_CELLS integers
Definition at line 50 of file sudoku_utils.c.
References initial_grid, SUDOKU_CELLS, and SUDOKU_SIZE.
Referenced by main().
sudoku_not_equal_checker()
static bool sudoku_not_equal_checker (const CSPConstraint * constraint, const size_t * values, const void * data) static
Checker function for Sudoku not-equal constraints (binary constraints)
Definition at line 43 of file sudoku_utils.c.
References csp_constraint_get_variable().
Referenced by create_sudoku_problem().
sudoku_preassigned_checker()
static bool sudoku_preassigned_checker (const CSPConstraint * constraint, const size_t * values, const void * data) static
Checker function for Sudoku unary constraints (pre-assigned values)
This function is used to ensure that values pre-assigned in the original Sudoku grid are respected in the solution. When the data pointer is NULL, we simply return true since there are no pre-assigned values to enforce.
Definition at line 16 of file sudoku_utils.c.
References csp_constraint_get_variable(), and initial_grid.
Referenced by create_sudoku_problem().