CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-solve-sudoku-integration.c File Reference
test-solve-sudoku-integration.c File Reference
#include <assert.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "../src/csp.h"
#include "../src/forward-checking.h"
#include "../src/sudoku_utils.h"
Functions
void check_block_uniqueness (const size_t *solution, size_t block_row, size_t block_col)
static void handle_timeout (int sig)
int main ()
Variables
volatile sig_atomic_t timeout_occurred
Recursive backtracking function with forward checking.
Function Documentation
check_block_uniqueness()
void check_block_uniqueness (const size_t * solution, size_t block_row, size_t block_col)
Integration test for the Sudoku solver:
Reads a Sudoku puzzle from a string
Creates a CSP problem from the grid
Solves the problem using forward checking
Verifies the solution
Definition at line 179 of file test-solve-sudoku-integration.c.
References SUDOKU_SIZE.
Referenced by main().
handle_timeout()
static void handle_timeout (int sig) static
Definition at line 17 of file test-solve-sudoku-integration.c.
References timeout_occurred.
Referenced by main().
main()
int main (void)
Definition at line 35 of file test-solve-sudoku-integration.c.
References check_block_uniqueness(), create_sudoku_problem(), csp_finish(), csp_init(), csp_problem_destroy(), csp_problem_solve_forward_checking(), handle_timeout(), read_sudoku_puzzle(), SUDOKU_CELLS, SUDOKU_SIZE, and timeout_occurred.
Variable Documentation
timeout_occurred
volatile sig_atomic_t timeout_occurred extern
Recursive backtracking function with forward checking.
This function implements the core of the forward checking algorithm:
Check if all variables are assigned - if so, return success
Select the next unassigned variable using the MRV heuristic
Order the values for this variable using the LCV heuristic
Try each value in order: a. Assign the value to the variable b. Check if the assignment is consistent c. Prune inconsistent values from future variables d. Recursively try to assign the remaining variables e. If successful, return the solution f. If unsuccessful, restore pruned values and try the next value
Parameters
csp The CSP problem to solve.
values Array to store the assignments of values to variables.
data User-provided data for constraint checking.
ctx The forward checking context.
Returns
true if a solution is found, false otherwise.
Definition at line 13 of file forward-checking.c.
Referenced by backtrack_fc(), handle_timeout(), and main().