CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-prune-neighbors.c File Reference
test-prune-neighbors.c File Reference
#include <assert.h>
#include <stdio.h>
#include "../src/csp.h"
#include "../src/forward-checking.h"
#include "../src/heuristics.h"
Functions
static bool diff (CSPConstraint const *c, const size_t *v, const void *data)
int main (void)
void test_prune_neighbors (void)
Function Documentation
diff()
static bool diff (CSPConstraint const * c, const size_t * v, const void * data) static
Definition at line 8 of file test-prune-neighbors.c.
References csp_constraint_get_variable().
Referenced by test_prune_neighbors().
main()
int main (void)
Definition at line 46 of file test-prune-neighbors.c.
References test_prune_neighbors().
test_prune_neighbors()
void test_prune_neighbors (void)
Definition at line 15 of file test-prune-neighbors.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_finish(), csp_forward_check_context_create(), csp_forward_check_context_destroy(), csp_init(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), diff(), prune_neighbors(), and restore_pruned().
Referenced by main().