CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-order-values-lcv.c File Reference
test-order-values-lcv.c File Reference
#include <assert.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include "../src/csp.h"
#include "../src/forward-checking.h"
#include "../src/heuristics.h"
Functions
int main (void)
static bool sumLeq (CSPConstraint const *c, const size_t *v, const void *d)
void test_lcv_basic (void)
Function Documentation
main()
int main (void)
Definition at line 58 of file test-order-values-lcv.c.
References test_lcv_basic().
sumLeq()
static bool sumLeq (CSPConstraint const * c, const size_t * v, const void * d) static
Definition at line 11 of file test-order-values-lcv.c.
References csp_constraint_get_variable().
Referenced by test_lcv_basic().
test_lcv_basic()
void test_lcv_basic (void)
Definition at line 17 of file test-order-values-lcv.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_finish(), csp_forward_check_context_create(), csp_forward_check_context_destroy(), csp_init(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), order_values_lcv(), and sumLeq().
Referenced by main().