CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-context.c File Reference
test-context.c File Reference
#include <assert.h>
#include <stdio.h>
#include "../src/csp.h"
#include "../src/forward-checking.h"
Functions
int main (void)
void test_context_create_destroy (void)
Function Documentation
main()
int main (void)
Definition at line 33 of file test-context.c.
References test_context_create_destroy().
test_context_create_destroy()
void test_context_create_destroy (void)
Definition at line 6 of file test-context.c.
References _CSPForwardCheckContext::assigned, csp_finish(), csp_forward_check_context_create(), csp_forward_check_context_destroy(), csp_init(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_domain(), _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by main().