CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-constraint.c File Reference
test-constraint.c File Reference
#include <stdlib.h>
#include "../src/csp.h"
#include <assert.h>
Functions
bool dummy_check (const CSPConstraint *constraint, const size_t *values, const void *data)
int main (void)
Function Documentation
dummy_check()
bool dummy_check (const CSPConstraint * constraint, const size_t * values, const void * data)
Definition at line 10 of file test-constraint.c.
Referenced by main().
main()
int main (void)
Definition at line 14 of file test-constraint.c.
References csp_constraint_create(), csp_constraint_destroy(), csp_constraint_get_arity(), csp_constraint_get_check(), csp_constraint_get_variable(), csp_finish(), csp_init(), and dummy_check().