CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-problem-is-consistent.c File Reference
test-problem-is-consistent.c File Reference
#include <stdlib.h>
#include "../src/csp.h"
#include <assert.h>
Functions
bool different (const CSPConstraint *constraint, const size_t *values, const void *data)
int main (void)
Function Documentation
different()
bool different (const CSPConstraint * constraint, const size_t * values, const void * data)
Definition at line 10 of file test-problem-is-consistent.c.
References csp_constraint_get_variable().
Referenced by main().
main()
int main (void)
Definition at line 17 of file test-problem-is-consistent.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_finish(), csp_init(), csp_problem_backtrack(), csp_problem_create(), csp_problem_destroy(), csp_problem_get_constraint(), csp_problem_is_consistent(), csp_problem_set_constraint(), csp_problem_set_domain(), and different().