CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-problem.c File Reference
test-problem.c File Reference
#include <stdlib.h>
#include "../src/csp.h"
#include <assert.h>
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 9 of file test-problem.c.
References csp_finish(), csp_init(), csp_initialised(), csp_problem_create(), csp_problem_destroy(), csp_problem_get_constraint(), csp_problem_get_domain(), csp_problem_get_num_constraints(), and csp_problem_get_num_domains().