CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-select-unassigned-var.c File Reference
test-select-unassigned-var.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../src/forward-checking.h"
#include "../src/heuristics.h"
Functions
static void destroy_ctx (CSPForwardCheckContext *ctx)
int main (void)
static CSPForwardCheckContext * make_ctx (size_t n, const size_t *domains, const bool **mask, const bool *assigned)
void test_mrv_simple (void)
void test_mrv_skip_assigned (void)
Function Documentation
destroy_ctx()
static void destroy_ctx (CSPForwardCheckContext * ctx) static
Definition at line 24 of file test-select-unassigned-var.c.
References _CSPForwardCheckContext::assigned, _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by test_mrv_simple(), and test_mrv_skip_assigned().
main()
int main (void)
Definition at line 65 of file test-select-unassigned-var.c.
References test_mrv_simple(), and test_mrv_skip_assigned().
make_ctx()
static CSPForwardCheckContext * make_ctx (size_t n, const size_t * domains, const bool ** mask, const bool * assigned) static
Definition at line 8 of file test-select-unassigned-var.c.
References _CSPForwardCheckContext::assigned, _CSPForwardCheckContext::current_domains, _CSPForwardCheckContext::num_domains, and _CSPForwardCheckContext::original_domain_sizes.
Referenced by test_mrv_simple(), and test_mrv_skip_assigned().
test_mrv_simple()
void test_mrv_simple (void)
Definition at line 33 of file test-select-unassigned-var.c.
References destroy_ctx(), make_ctx(), and select_unassigned_var().
Referenced by main().
test_mrv_skip_assigned()
void test_mrv_skip_assigned (void)
Definition at line 49 of file test-select-unassigned-var.c.
References destroy_ctx(), make_ctx(), and select_unassigned_var().
Referenced by main().