CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-forward-checking.c File Reference
test-forward-checking.c File Reference
#include <assert.h>
#include <stdio.h>
#include "../src/csp.h"
#include "../src/csp_internal.h"
#include "../src/forward-checking.h"
Functions
static bool always_true (const CSPConstraint *c, const size_t *v, const void *d)
static bool diff (const CSPConstraint *constraint, const size_t *values)
int main (void)
static bool sumLeq (const CSPConstraint *constraint, const size_t *values, const void *data)
void test_single_var (void)
void test_three_var_diff (void)
void test_two_var_diff (void)
void test_unsatisfiable (void)
void test_with_data (void)
Function Documentation
always_true()
static bool always_true (const CSPConstraint * c, const size_t * v, const void * d) static
Definition at line 25 of file test-forward-checking.c.
Referenced by test_single_var().
diff()
static bool diff (const CSPConstraint * constraint, const size_t * values) static
Definition at line 10 of file test-forward-checking.c.
References csp_constraint_get_variable().
Referenced by test_three_var_diff(), test_two_var_diff(), and test_unsatisfiable().
main()
int main (void)
Definition at line 121 of file test-forward-checking.c.
References csp_finish(), csp_init(), test_single_var(), test_three_var_diff(), test_two_var_diff(), test_unsatisfiable(), and test_with_data().
sumLeq()
static bool sumLeq (const CSPConstraint * constraint, const size_t * values, const void * data) static
Definition at line 16 of file test-forward-checking.c.
References csp_constraint_get_variable().
Referenced by test_with_data().
test_single_var()
void test_single_var (void)
Definition at line 32 of file test-forward-checking.c.
References always_true(), csp_constraint_create(), csp_constraint_set_variable(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), and csp_problem_solve_forward_checking().
Referenced by main().
test_three_var_diff()
void test_three_var_diff (void)
Definition at line 80 of file test-forward-checking.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), csp_problem_solve_forward_checking(), and diff().
Referenced by main().
test_two_var_diff()
void test_two_var_diff (void)
Definition at line 47 of file test-forward-checking.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), csp_problem_solve_forward_checking(), and diff().
Referenced by main().
test_unsatisfiable()
void test_unsatisfiable (void)
Definition at line 64 of file test-forward-checking.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), csp_problem_solve_forward_checking(), and diff().
Referenced by main().
test_with_data()
void test_with_data (void)
Definition at line 104 of file test-forward-checking.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), csp_problem_solve_forward_checking(), and sumLeq().
Referenced by main().