CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-create-sudoku-problem.c File Reference
test-create-sudoku-problem.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../src/csp.h"
#include "../src/sudoku_utils.h"
Functions
int main ()
Function Documentation
main()
int main (void)
Tests for the create_sudoku_problem function
Definition at line 12 of file test-create-sudoku-problem.c.
References create_sudoku_problem(), csp_constraint_get_arity(), csp_constraint_get_variable(), csp_finish(), csp_init(), csp_problem_destroy(), csp_problem_get_constraint(), csp_problem_get_domain(), csp_problem_get_num_constraints(), csp_problem_get_num_domains(), SUDOKU_CELLS, and SUDOKU_SIZE.