CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-solve-forward-checking.c File Reference
test-solve-forward-checking.c File Reference
#include <assert.h>
#include <stdio.h>
#include "../src/csp.h"
#include "../src/forward-checking.h"
Functions
static bool diff (CSPConstraint const *c, const size_t *v, const void *data)
int main (void)
void test_solve_simple (void)
Function Documentation
diff()
static bool diff (CSPConstraint const * c, const size_t * v, const void * data) static
Definition at line 8 of file test-solve-forward-checking.c.
References csp_constraint_get_variable().
Referenced by test_solve_simple().
main()
int main (void)
Definition at line 36 of file test-solve-forward-checking.c.
References test_solve_simple().
test_solve_simple()
void test_solve_simple (void)
Definition at line 15 of file test-solve-forward-checking.c.
References csp_constraint_create(), csp_constraint_set_variable(), csp_finish(), csp_init(), csp_problem_create(), csp_problem_destroy(), csp_problem_set_constraint(), csp_problem_set_domain(), csp_problem_solve_forward_checking(), and diff().
Referenced by main().