CSP-lib: Constraint Satisfaction Problem Solver Library: tests/test-constraint-to-check.c File Reference
test-constraint-to-check.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "../src/csp.h"
#include <assert.h>
Functions
bool dummy_check (const CSPConstraint *constraint, const size_t *values, const void *data)
int main (void)
Function Documentation
dummy_check()
bool dummy_check (const CSPConstraint * constraint, const size_t * values, const void * data)
Definition at line 11 of file test-constraint-to-check.c.
Referenced by main().
main()
int main (void)
Definition at line 18 of file test-constraint-to-check.c.
References csp_constraint_create(), csp_constraint_destroy(), csp_constraint_set_variable(), csp_constraint_to_check(), csp_finish(), csp_init(), and dummy_check().